AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudresumecounter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  TableNameParameter:
    Type: String
    Default: "CloudResumeCounterHits"

Resources:
  CounterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBWritePolicy:
            TableName:
              Ref: TableNameParameter
      CodeUri: counter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
          DYNAMODB_TABLE:
            Ref: TableNameParameter
      Events:
        Counter:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId:
              !Ref CounterApi
            Path: /counter
            Method: get
  CounterApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - "*"
        AllowOrigins:
          - "*"
      DefaultRouteSettings:
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 10
  CounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "path"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "path"
          KeyType: "HASH"
      TableName:
        Ref: TableNameParameter
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CounterApi:
    Description: "API Gateway endpoint URL for $default stage for Counter function"
    Value: !Sub "https://${CounterApi}.execute-api.${AWS::Region}.amazonaws.com/counter"
  CounterFunction:
    Description: "Counter Lambda Function ARN"
    Value: !GetAtt CounterFunction.Arn
  CounterFunctionIamRole:
    Description: "Implicit IAM Role created for Counter function"
    Value: !GetAtt CounterFunctionRole.Arn
  CounterTable:
    Description: "Counter DynamoDB Table"
    Value: !GetAtt CounterTable.Arn
